/* Generated By:JavaCC: Do not edit this line. JSONParserTreeConstants.java Version 5.0 */
package org.mwnorman.json;

@SuppressWarnings("all")
public interface JSONParserTreeConstants
{
  public int JJTPARSE = 0;
  public int JJT_OBJECT = 1;
  public int JJTMEMBERS = 2;
  public int JJTPAIR = 3;
  public int JJTFIELDNAME = 4;
  public int JJT_ARRAY = 5;
  public int JJTELEMENTS = 6;
  public int JJTVALUE = 7;


  public String[] jjtNodeName = {
    "parse",
    "_object",
    "members",
    "pair",
    "fieldName",
    "_array",
    "elements",
    "value",
  };
}
/* JavaCC - OriginalChecksum=7e8f96d85c6a2ff404d43c5d73bf900f (do not edit this line) */
