/* Generated By:JavaCC: Do not edit this line. JSONParserTreeConstants.java Version 5.0 */
package org.mwnorman.json;

@SuppressWarnings("all")
public interface JSONParserTreeConstants
{
  public int JJTPARSE = 0;
  public int JJTOBJECT = 1;
  public int JJTMEMBERS = 2;
  public int JJTPAIR = 3;
  public int JJTFIELDNAME = 4;
  public int JJTSTRIPOFFQUOTES = 5;
  public int JJTARRAY = 6;
  public int JJTELEMENTS = 7;
  public int JJTVALUE = 8;


  public String[] jjtNodeName = {
    "parse",
    "object",
    "members",
    "pair",
    "fieldName",
    "stripOffQuotes",
    "array",
    "elements",
    "value",
  };
}
/* JavaCC - OriginalChecksum=cbb0825fc94ab7ee1bade61e77c65d57 (do not edit this line) */
